language: java
sudo: false
install: true

#addons:
#  sonarcloud:
#    organization: "sonarsource"
#    token:
#      secure: ""

jdk:
  - openjdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn cobertura:cobertura
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
#        -Dsonar.host.url=https://sonarcloud.io \
#        -Dsonar.organization=hyeonil-github \
#        -Dsonar.login=

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)