language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sonarsource"
    token:
      secure: ""

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=hyeonil-github \
        -Dsonar.login=

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'